#cloud-config
runcmd:
 - mkdir /run/iwuzhere
 - git clone https://github.com/sihde/mcazure.git /root/mcazure && cd /root/mcazure/setup && ./setup-vpn.sh >setup.log 2>setup.err

package_upgrade: true
packages:
#  - puppet
#  - puppet-module-puppetlabs-apt
  - git
